#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Project: Plone REST API Agent Skills Enhancement

set -e

echo "========================================"
echo "Plone REST API Skills - Environment Check"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# VERIFY PROJECT STRUCTURE
# ============================================

echo ""
echo "Checking project structure..."

# Check skill directories exist
if [ -d ".claude/skills/plone-restapi-backend" ]; then
    echo -e "${GREEN}✓${NC} Backend skill directory exists"
else
    echo -e "${RED}✗${NC} Backend skill directory missing"
    exit 1
fi

if [ -d ".claude/skills/plone-restapi-client" ]; then
    echo -e "${GREEN}✓${NC} Client skill directory exists"
else
    echo -e "${RED}✗${NC} Client skill directory missing"
    exit 1
fi

# Check SKILL.md files exist
if [ -f ".claude/skills/plone-restapi-backend/SKILL.md" ]; then
    echo -e "${GREEN}✓${NC} Backend SKILL.md exists"
else
    echo -e "${RED}✗${NC} Backend SKILL.md missing"
    exit 1
fi

if [ -f ".claude/skills/plone-restapi-client/SKILL.md" ]; then
    echo -e "${GREEN}✓${NC} Client SKILL.md exists"
else
    echo -e "${RED}✗${NC} Client SKILL.md missing"
    exit 1
fi

# ============================================
# VERIFY btca TOOL
# ============================================

echo ""
echo "Checking btca tool availability..."

if command -v btca &> /dev/null; then
    echo -e "${GREEN}✓${NC} btca tool is available"
    btca --version 2>/dev/null || echo "  (version check not supported)"
else
    echo -e "${YELLOW}!${NC} btca tool not found in PATH"
    echo "  btca is required for documentation research phase"
    echo "  Install from: https://github.com/ArnoClaworker/btca"
fi

# Check btca config
if [ -f "btca.config.jsonc" ]; then
    echo -e "${GREEN}✓${NC} btca config file exists"
else
    echo -e "${YELLOW}!${NC} btca.config.jsonc not found"
fi

# ============================================
# CURRENT SKILL STATUS
# ============================================

echo ""
echo "========================================"
echo "Current Skill Statistics"
echo "========================================"

backend_lines=$(wc -l < .claude/skills/plone-restapi-backend/SKILL.md)
backend_ref_lines=$(wc -l < .claude/skills/plone-restapi-backend/reference.md)
client_lines=$(wc -l < .claude/skills/plone-restapi-client/SKILL.md)
client_ref_lines=$(wc -l < .claude/skills/plone-restapi-client/reference.md)

echo "Backend Skill:"
echo "  - SKILL.md: $backend_lines lines"
echo "  - reference.md: $backend_ref_lines lines"

echo "Client Skill:"
echo "  - SKILL.md: $client_lines lines"
echo "  - reference.md: $client_ref_lines lines"

# Count endpoints in client skill
endpoint_count=$(grep -c '| `@' .claude/skills/plone-restapi-client/SKILL.md 2>/dev/null || echo "0")
echo ""
echo "Documented @-endpoints: $endpoint_count"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "This is a documentation project - no services to start."
echo ""
echo "Next steps:"
echo "  1. Use btca to research Plone REST API documentation"
echo "  2. Identify gaps in current skill coverage"
echo "  3. Enhance skill files with missing content"
echo ""
echo "Example btca commands:"
echo "  btca ask -r ploneRestapi -q 'List all REST API endpoints'"
echo "  btca ask -r ploneRestapi -q 'How to create custom services'"
echo ""
